### ISSUE TITLE
WET 4.0 documentation stream planning

### ISSUE THREAD

**Issue by salmonz** [wet-boew/wet-boew#3290]
### Analysis
TBD

### Code
- [ ] ID/class glossary
- [ ] Building WxT4 on Windows
- [ ] Building WxT4 on Mac OSX

### Test
TBD

## Timelines
TBD

## Required skills for resources (ranking)
TBD

**Comment by hsrudnicki** [comment]
Can be this issue closed as well ?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue, opened in 2013 and last commented in 2014, can be closed or otherwise? Thanks

**Comment by hsrudnicki** [comment]
Due to no further discussion or status updates, this issue has been labeled as "Going Stale" and closed.
