### ISSUE TITLE
Feeds: Add pagination to social media feeds

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6173]
# TODO:

## General
* [ ] Don't force "generic" parameter for parseEntries when clicking next/previous links.
* [ ] Make clicking the next/previous links focus on the list instead of jumping to the top of the page.
* [ ] Prevent pagination markup from getting injected when it isn't needed (Many feeds currently take in more entries than the load-* limit, which tricks the plugin into unnecessarily enabling pagination.)

## Improve accessibility:
* [ ] Add hidden link text based on feed titles in next/previous links (e.g. "Next: Title of feed").
* [ ] Add ARIA roles?
* [ ] Completely remove disabled next/previous links from DOM?

**Comment by hsrudnicki** [comment]
@LaurentGoderre @thomasgohard @EricDunsworth : Can be this issue closed?

**Comment by hsrudnicki** [comment]
Please keep posted this issue's status and close this issue when ready, thanks

**Comment by hsrudnicki** [comment]
Moved to v4.0.19 or when otherwise? Either way, please keep this issue's status updated, thank you

**Comment by EricDunsworth** [comment]
I think only @thomasgohard would know if there's still a need to add pagination to the feeds plugin.

As far as the state of the addition itself, a "feeds-pagination" branch was created in the wet-boew repo and some work went into it - but was never completed. I believe what's currently there partially works but is broken for certain types of feeds. Unfortunately, neither I nor @fsnoddy have capacity to work on it at this time :(.

**Comment by hsrudnicki** [comment]
Made "Going Stale", based on the above, and @thomasgohard and others, can be this issue closed or otherwise?  Either way, please update this issue's status again, thank you

**Comment by hsrudnicki** [comment]
Can be this issue closed as resolved/fixed, based on the given milestone(s) or if it's still an issue, waiting for a response from @thomasgohard to resolve it ?  Either way, please update this issue's status, whether this issue can be closed as fixed or if otherwise?  Thank you

**Comment by hsrudnicki** [comment]
Please update this issue's status/milestone for this current year as well, thank you

**Comment by hsrudnicki** [comment]
Does this remain still an open issue or otherwise? Please update the status/milestone of this for this year as well, thx

**Comment by hsrudnicki** [comment]
Due to the above, this issue of 2014 year can be closed. If you think otherwise, please update the status of this again, thank you
